name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull taltaf913/plant-fastapi-mini:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f plant-fastapi-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8001:8001 --name plant-fastapi-container taltaf913/plant-fastapi-mini
